### ISSUE TITLE
“TypeError: Object doesn't support property or method 'find'” in Internet Explorer (IE) 11

### ISSUE THREAD

**Issue by luckygulli** [oklas/react-through#1]
Hello,

Is it possible to add IE11 compatibility?

Using IE11, I get the following error:

 1. Find

    >TypeError: Object doesn't support property or method 'find'
    >hasComplex
    >hasComplex.js:14

    The method `find` is not supported by IE according to [mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Browser_compatibility).
    This could be corrected by adding [Polyfill method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfill) even if Mozilla says:
    > If you need to support truly obsolete JavaScript engines that don't support `Object.defineProperty`, it's best not to polyfill `Array.prototype` methods at all, as you can't make them non-enumerable.

 2. Includes

    Then, you'll get the following error:

    >TypeError: Object doesn't support property or method 'includes'
    >hasComplex
    >hasComplex.js:19

    The method `includes` is not supported by IE according to [mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Browser_compatibility).
    This could be corrected by adding [Polyfill method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Polyfill) even if Mozilla says:
    > If you need to support truly obsolete JavaScript engines that don't support `Object.defineProperty`, it's best not to polyfill `Array.prototype` methods at all, as you can't make them non-enumerable.

That's all. You could maybe alternatively use JQuery.

Thanks.

**Comment by jkeruzec** [comment]
Interested in this one too !
edit: added it in lib directly and it works perfect!

**Comment by oklas** [comment]
Have a nice day. Thank you for contribution. Most probably your another components will require this functions too, so to avoid code duplication use a polyfills like `ie-array-find-polyfill` and `es6-object-assign`. or better use a `babel-polyfill`.

**Comment by jkeruzec** [comment]
#3 

Add new PR

**Comment by oklas** [comment]
The package `babel polyfill` collects all the features which may not exists by default. It is possible to integrate all of that features at once or separately only that features which is required. It works quck and size is tiny. There is no any necessity to duplicate that features to some library else. The polyfill enabling is the task of the application unless any library because **polyfill must be enabled once at the entry point of the application**.

The simplest way to use is importing the `babel polyfill` at the begin of the application before any other modules:

```js
import "@babel/polyfill"
```

For example the demo application uses babel polyfill at [this line](https://github.com/oklas/react-breadcrumbs-dynamic/blob/6cdbc5fddedaa4dc0301e72b51f92e8a0accdd8d/example/src/index.js#L1) and [works in ie11](https://oklas.github.io/react-breadcrumbs-dynamic)
